### ISSUE TITLE
Availpro API

### ISSUE THREAD

**Issue by jeromeDms** [thermesmarins/tmsm-availpro#1]
Hi
I'm interested in your plugin for the site of our hotel.
I cannot find a link to get information about Availpro API.
I searched on d-edge website without success.
Can you help ?
Thanks

**Comment by nicomollet** [comment]
Hello @jeromeDms 

Unfortunately, AvailPro/D-Edge doesn't have a public documentation for the API.

Also, they make you pay for the API on your contract...
And you have to ask for the documentation (good old PDFs you know).

The web service is SOAP only as far as I know, no REST.

I guess you should ask your account manager about it?

Hope that helps.
Nico

**Comment by jeromeDms** [comment]
Hi Nico,
I called D-EDGE yesterday and they do not provide access to their API, unless you are referenced as a "compliant web developer". 
They have some contractors for this, and thus, you have to pay to access their API, even if you are a developer !
My idea was to access their API to display our best price on our hotel website, without having to use the booking engine.
And my other idea was to implement the bridge between availpro and google hotel ads so our hotel can appear in google booking engine.
No way to implement the above without paying again !

**Comment by jeromeDms** [comment]
BTW I'm French too ;-)

**Comment by nicomollet** [comment]
Salut Jérome !

La pratique de D-Edge concernant l'API est assez minable.
Nous, l'API était apparemment dans notre contrat (qui a plusieurs années), donc on n'a pas payé de "supplément" pour ça mais c'était genre 5k si je me souviens bien (!).
Ils ne veulent pas qu'on l'utilise ? N'importe quoi.

A l'heure actuelle, on me dit que la connexion D-Edge Google Hotel Ads ne nous coûte que la commission Google. Et qu'il y avait eu un (léger) coût pour le setup.

Ce repository est juste un plugin WordPress qui ne fait qu'afficher les prix dans un calendrier, vois le en action sur : https://www.le-grand-hotel-des-thermes.fr/
Nous on n'a pas l'intention de remplacer le booking engine à ce jour.
Ils étaient supposés lui donner un coup de jeune mais ça n'arrive pas...

Bon courage à toi

**Comment by jeromeDms** [comment]
Effectivement le plugin a tout son intérêt.
Mais nous n'avons pas le droit d'accéder à leur API, malgré mon insistance hier au tel.

Ce qu'ils nous proposent pour google Hotel Ads est une comm de 10% sur les ventes, plus 20€ d'abonnement, plus des frais de mise en place d'une centaine d'€.
Je suis étonné de voir des comm sur google, il me semble que ce n'est pas la politique google que de commissioner les ventes, le business model de google est plutôt d'offrir ses services et de se rémunérer sur la pub, étant donné qu'ils offrent la possibilité aux hotels de promouvoir leur établissement.

Vu que de ton coté tu as accès a l'API D-Edge, pourquoi ne pas développer le bridge entre l'API google Hotel et l'API D-Edge ? Ca t'éviterait ces commissions...

**Comment by jeromeDms** [comment]
La page avec :

```
Meilleur tarif garanti
Réservez une chambre :
Du 29/11/2021 au 30/11/2021
Nombre de nuits : 1
À partir de xxx € sur notre site officiel

Réserver maintenant

Si vous réservez ailleurs :
À partir de zzz € : Booking.com
À partir de zzz € : Expedia
À partir de zzz € : Tripadvisor

```
Tu as pu la construire grace à l'API qui te permet de récupérer les tarifs booking etc ?

**Comment by jeromeDms** [comment]
La page avec :

```
Meilleur tarif garanti
Réservez une chambre :
Du 29/11/2021 au 30/11/2021
Nombre de nuits : 1
À partir de xxx € sur notre site officiel

Réserver maintenant

Si vous réservez ailleurs :
À partir de zzz € : Booking.com
À partir de zzz € : Expedia
À partir de zzz € : Tripadvisor

```
Tu as pu la construire grace à l'API qui te permet de récupérer les tarifs booking etc ?

**Comment by nicomollet** [comment]
Je me suis renseigné auprès de l'équipe qui gère les ads, et il y a bien des comms Google.
Moi-même j'ai du mal à voir la différence entre Hotel Ads et Hotel Finder.
Je n'ai apparemment pas accès à toutes les API, et puis certains développement me semblent plutôt lourds en fait.

Mais oui, on a dans D-Edge, notre tarif officiel et le tarif "OTA". 
Avec l'API je peux récupérer les tarifs que je veux.
C'est un dév que j'ai orienté pour nous (le Groupe des Thermes Marins), seuls nous l'utilisons pour info.
